server:
  port: 8761
<<<<<<< HEAD

eureka:
=======
spring:
  application:
    name: FoodieServiceRegistry
eureka:

>>>>>>> master
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false