server:
  port: 8083
<<<<<<< HEAD
spring:
  application:
    name: FOODIE-ORDER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/orderservice
    username: root
    password: 1234
=======

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodieService
    username: root
    password: Drc@1234
>>>>>>> master
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
<<<<<<< HEAD

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
=======
  application:
    name:  FOODIE-ORDER-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
>>>>>>> master

