server:
  port: 8080

spring:
  application:
    name: FOODIE-GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: FOODIE-USER-SERVICE
          uri: lb://FOODIE-USER-SERVICE
          predicates:
            - Path=/auth/login,/users/**,/create/**

        - id: FOODIE-HOTEL-SERVICE
          uri: lb://FOODIE-HOTEL-SERVICE
          predicates:
            - Path=/hotel/**,/items/**

        - id: FOODIE-ORDER-SERVICE
          uri: lb://FOODIE-ORDER-SERVICE
          predicates:
            - Path=/orders/**
  config:
    import: optional:configserver:http://localhost:8085


